### ISSUE TITLE
Status of best 'x' and 'y'

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/biologic-converter#28]
What is the current status to try to place in the 'x' and 'y' variable the more likely interesting variable depending the technique ?

https://analysis-ui-components.pages.dev/pages/demo#?filelist=https%3A%2F%2Fzakodium-oss.github.io%2Fanalysis-dataset%2Fbigmap.json

I added a 'bigmap.json' dataset (just 2 of the biologic files) but x versus y gives error on 'x' as default variable.

<img width="871" alt="image" src="https://user-images.githubusercontent.com/1484241/201433726-e3420873-44cb-45ee-98cb-e0afdfb19b22.png">

**Comment by santimirandarp** [comment]
yes, it is done for CA, CP, and CV I think, the problem is that CA can be 2 techniques. But if you get error is for not implemented ones. This is actually done in A-UI, I did it like this so we could update it without depending on the biologic.

**Comment by santimirandarp** [comment]
You can take a look at the [preview here ](https://harmonise-parsers.analysis-ui-components.pages.dev/pages/demo#?filelist=https%3A%2F%2Fzakodium-oss.github.io%2Fanalysis-dataset%2Fbiologic.json)(warning: url parameters set to call for Biologic data). 

For CA, try to zoom in close to x=0, you will notice that there is more data about current. We could discuss the default if that isn't what we want. 

This is done in the UI currently, I think it is handy because whenever we change defaults, we can view them and play with the labels. We could move all the code back to the parser once we are happy with it.
